#!/bin/bash

for c0 in 0; do
  for c1 in 0 10; do
    for c2 in 0 10 110; do
      for c3 in 0 10 110 1110; do
        vec="${c0}${c1}${c2}${c3}"
        bv=`echo ${vec} | rev`
        fn="mbedtls_mpi_mul_mpi_4limbs_${vec}"
        echo "Generating ${fn}.cl"

        echo "  Compiling code"
        sed -e "s/INDEX_TEMPLATE/0b${bv}/g" library/bignum_template.c > library/bignum.c
        make &> /dev/null
        ./compile

        echo "  Extracting trace"
        ./extract

        echo "  Cleaning trace"
        ./clean_gas.py trace.gas ${vec} > ${fn}.gas
        ./tocl ${fn}.gas > trace.cl
        ./clean_cl.py trace.cl > ${fn}.cl
      done
    done
  done
done

for c0 in 0; do
  for c1 in 0 10; do
    for c2 in 0 10 110; do
      for c3 in 0 10 110 1110; do
        vec="${c0}${c1}${c2}${c3}"
        fn="mbedtls_mpi_mul_mpi_4limbs_${vec}"
        echo "Verifying ${fn}.cl"
        ./verify ${fn}.cl &> ${fn}.log
      done
    done
  done
done
