
open Options.Std
open Ast.Cryptoline
(*open Ast.MultiTrack
  open Smt*)
open Common
open Utils
open Utils.Std

(* Apply a verification function to cuts.
   @param ids IDs of cuts to be verified
   @param f verification function
   @param delivered_helper a function merging verification results
   @param res the current result
   @param pending the pending state
   @param ss a list [s0; s1; ...; sN] where each si is a list of
             specifications in cut i *)
let apply_to_cuts_domains ids f delivered_helper res pending ss =
  let ids = ids
            |> Option.map Hashset.to_list
            |> Option.map (List.rev_map (normalize_index (List.length ss)))
            |> Option.map List.rev
            |> Option.map Hashset.of_list in
  let rec helper i (res, pending) ss =
    match ss with
    | [] -> DomainsTasks.finish_pending delivered_helper res pending
    | hd::tl ->
       if Options.Std.mem_hashset_opt ids i
       then let headers = [ "=== Cut #" ^ string_of_int i ^ " ===" ] in
            let (res, pending) =
              List.fold_left (f i headers) (res, pending) hd in
            helper (i+1) (res, pending) tl
       else let _ =
              if !Options.Std.debug then
                DomainsTasks.log_with_lock ("=== Skip Cut #" ^ string_of_int i ^ " ===\n") in
            helper (i+1) (res, pending) tl in
  helper 0 (res, pending) ss

(* Run commands safely with Domains. *)
let exec_cmd_domains ?ofile cmd_array =
  let (out, err, fds_to_close) =
    match ofile with
    | None -> (Unix.stdout, Unix.stderr, [])
    | Some file ->
      let out_fd = Unix.openfile file [Unix.O_WRONLY; Unix.O_CREAT; Unix.O_TRUNC] 0o644 in
      (out_fd, out_fd, [out_fd]) in
  let pid =
    Unix.create_process cmd_array.(0) cmd_array
      Unix.stdin out err in
  let (_, status) = Unix.waitpid [] pid in
  let _ = List.iter Unix.close fds_to_close in
  match status with
  | Unix.WSIGNALED n when n = Sys.sigkill ->
    raise Tasks.TimeoutException
  | _ -> status

(* Converting a string of command-line arguments to a list. *)
let args_from_string str =
  String.split_on_char ' ' str
  |> List.filter (fun s -> s <> "")

(** Write input to Singular using Buffer and Out_channel. *)
let write_singular_input ?comments ifile vars gen p =
  let buf = Buffer.create 1024 in
  let _ = Cas.bprint_singular_input ?comments buf vars gen p in
  Out_channel.with_open_bin ifile (
    fun ch ->
      Buffer.output_buffer ch buf
  )

(* Read output from Singular using In_channel with comments skipped. *)
let read_singular_output ofile =
  let rec read_skip_comment ch =
    let line = input_line ch in
    if String.sub line 0 (min 2 (String.length line)) = "//" then
      read_skip_comment ch
    else
      line in
  let line = In_channel.with_open_text ofile read_skip_comment in
  String.trim line

(* Write headers to log file. *)
let write_headers_to_log headers =
  List.iter (fun str ->
      DomainsTasks.log str;
      DomainsTasks.log "\n"
    ) headers

(* Run Singular in a compatible way. *)
let run_singular_domains headers ifile ofile =
  let t1 = Unix.gettimeofday() in
  let extra_args = args_from_string !Options.Std.algebra_solver_args in
  let cmd_list = [ !singular_path; "-q" ] @ extra_args @ [ifile] in
  let cmd_array = Array.of_list cmd_list in
  let _ = exec_cmd_domains ~ofile cmd_array in
  let t2 = Unix.gettimeofday() in
  if !debug then begin
    DomainsTasks.lock_log();
    write_headers_to_log headers;
    DomainsTasks.log "INPUT TO SINGULAR:\n";
    DomainsTasks.log_file ifile;
    DomainsTasks.log "\n";
    DomainsTasks.log ("Execution time of Singular: " ^ Options.Std.string_of_running_time t1 t2 ^ "\n");
    DomainsTasks.log "OUTPUT FROM SINGULAR:\n";
    DomainsTasks.log_file ofile;
    DomainsTasks.log "\n";
    DomainsTasks.unlock_log()
  end

(* Check if polynomial [p] is in the ideal generated by the polynoimals
   [ideal]. *)
let is_in_ideal_domains ?comments ?(expand=(!expand_poly)) ?(solver=(!algebra_solver)) headers vars ideal p =
  let ideal = if expand then tmap expand_eexp ideal else ideal in
  let p = if expand then expand_eexp p else p in
  let ifile = tmpfile "inputfgb_" "" in
  let ofile = tmpfile "outputfgb_" "" in
  let comments = rcons_comments_option comments ("Output file: " ^ ofile) in
  let res =
    match solver with
    | Singular ->
       let _ = write_singular_input ~comments ifile vars ideal p in
       let _ = run_singular_domains headers ifile ofile in
       let res = read_singular_output ofile in
       res = "0"
    | Sage ->
      (* The input file to Sage must have file extension ".sage". *)
      failwith("To be supported")
      (*
       let ifile = ifile ^ ".sage" in
       let _ = write_sage_input ~comments ifile vars ideal p in
       let _ = run_sage ifile ofile in
       let res = read_sage_output ofile in
       res = "true"
       *)
    | Magma ->
      failwith("To be supported")
      (*
       let _ = write_magma_input ~comments ifile vars ideal p in
       let _ = run_magma ifile ofile in
       let res = read_magma_output ofile in
       res = "0"
       *)
    | Mathematica ->
      failwith("To be supported")
        (*
       let _ = write_mathematica_input ~comments ifile vars ideal p in
       let _ = run_mathematica ifile ofile in
       let res = read_mathematica_output ofile in
       res = "0"
       *)
    | Macaulay2 ->
      failwith("To be supported")
        (*
       let _ = write_macaulay2_input ~comments ifile vars ideal p in
       let _ = run_macaulay2 ifile ofile in
       let res = read_macaulay2_output ofile in
       res = "0"
       *)
    | Maple ->
      failwith("To be supported")
        (*
       let _ = write_maple_input ~comments ifile vars ideal p in
       let _ = run_maple ifile ofile in
       let res = read_maple_output ofile in
       res = "true"
       *)
    | SMTSolver _ -> failwith ("Ideal membership queries are not supported by SMT solver.")
    | PPL | SCIP | ISL -> failwith ("Ideal membership queries are not supported by MIP solver.")
  in
  let _ = cleanup [ifile; ofile] in
  res

(* Verify a list of entailments. *)
let verify_entailments_domains ?comments ?(solver=(!algebra_solver)) headers entailments =
  List.fold_left
    (fun res (post, vars, ideal, p) ->
       if res then (
         if !Options.Std.check_eq_first &&
            is_in_ideal_domains
              ~comments:(
                if !debug then
                  append_comments_option comments
                    [ "Algebraic condition: " ^ string_of_ebexp post;
                      "Try: #0 (pure equality)" ]
                else
                  []
              )
              ~solver:solver headers vars [] p then true
         else is_in_ideal_domains
             ~comments:(
               if !debug then
                 append_comments_option comments
                   [ "Algebraic condition: " ^ string_of_ebexp post;
                     "Try: #1 (modular equality)" ]
               else
                 []
             )
             ~solver:solver headers vars ideal p
       )
       else res) true entailments

(* Verify an algebraic specification using a computer algebra system.
   Applied in this function:
   - converting to ideal membership problems,
   - polynomial rewriting,
   - solving *)
let verify_espec_single_conjunct_ideal_domains ?comments headers vgen s =
  let (_, entailments) = polys_of_espec vgen s in
  let solver = algebra_solver_of_prove_with (ebexp_prove_with_specs s.espost) in
  verify_entailments_domains ?comments ~solver:solver headers entailments

let verify_espec_single_conjunct_smt_domains _solver ?comments:_comments _headers _vgen _s =
  failwith("To be supported")

let verify_espec_single_conjunct_mip_domains ?comments:_comments _headers _vgen _s =
  failwith("To be supported")

(* Verify an algebraic specification. The solver used can be specified
   in the prove-with clauses of the specification.
   Applied in this function: slicing *)
let verify_espec_single_conjunct_domains ?comments headers vgen s hashopt =
  let verify =
    match algebra_solver_of_prove_with (ebexp_prove_with_specs s.espost) with
    | SMTSolver solver ->
      verify_espec_single_conjunct_smt_domains solver ?comments headers
    | PPL | SCIP | ISL ->
      verify_espec_single_conjunct_mip_domains ?comments headers
    | _ ->
      verify_espec_single_conjunct_ideal_domains ?comments headers in
  is_espec_trivial s || Deduce.espec_prover s ||
    (verify vgen (if !apply_slicing then slice_espec_ssa s hashopt else s))

let verify_espec_no_ecut_domains ?comments headers vgen s hashopt =
  if !Options.Std.two_phase_rewriting then
    let solver = algebra_solver_of_prove_with (ebexp_prove_with_specs s.espost) in
    let mk_task entailment =
      fun () ->
      verify_entailments_domains ?comments ~solver:solver headers [entailment] in
    let s = remove_trivial_epost s in
    (* We don't need the full is_espec_trivial test. espre_implies_espost and
       espost_in_assumes are considered in remove_trivial_epost. *)
    match s.espost with
    | [] -> []
    | (e, _)::[] ->
       let (s, sliced) =
         match e with
         | Eand _ -> (s, false)
         | _ ->
            (* If the postcondition is an atomic predicate, apply slicing at
               the beginning. *)
            (slice_espec_ssa s None, true) in
       (* Convert to ideal membership problems, rewriting and slicing (if the
          postcondition is a conjunction) are done in polys_of_espec_two_phase. *)
       let (_, entailments) = polys_of_espec_two_phase ~sliced:sliced vgen s in
       let tasks = tmap mk_task entailments in
       tasks
    | _ -> assert false
  else
    let verify_task tasks s =
      match s.espost with
      | [] -> tasks
      | _ ->
        let task =
          fun () ->
          verify_espec_single_conjunct_domains
            ?comments headers vgen s hashopt in
        task::tasks in
    List.fold_left verify_task [] (split_espec_post s) |> List.rev

(* The top function of verifying range specifications when !jobs > 1.
   @param vgen a variable generator
   @param s an algebraic specification
   @param hashopt
   @return [true] if the algebraic specification is verified successfully *)
let verify_espec_domains options vgen s hashopt =
  let _ =
    if !Options.Std.debug then
      DomainsTasks.log_with_lock "===== Verifying algebraic specifications =====\n" in
  let delivered_helper = (&&) in
  let mk_tasks ?comments headers s =
    verify_espec_no_ecut_domains ?comments headers vgen s hashopt in
  let verify_ands_domains ?comments headers (res, pending) s =
    DomainsTasks.add_to_pending Fun.id delivered_helper res
      pending (mk_tasks ?comments headers s) in
  (* Check previous result *)
  let verify cid headers (res, pending) (sid, s) =
    if res then
      verify_ands_domains
        ~comments:(
          if !debug then
            [ "Verify: algebraic specifications";
              Printf.sprintf "Track: %s" options.st_tag;
              Printf.sprintf "Cut: #%d" cid;
              Printf.sprintf "Algebraic specification #%d: %s" sid (string_of_ebexp_prove_with s.espost) ]
          else
            []
        )
        headers (res, pending) s
    else (res, pending) in
  apply_to_cuts_domains options.st_verify_ecuts
    verify (&&) true (DomainsTasks.empty_pending()) (cut_espec s)

(* The top function of verifying algebraic assertions when !jobs > 1. *)
let verify_eassert_domains options vgen s hashopt =
  let _ =
    if !Options.Std.debug then
      DomainsTasks.log_with_lock "===== Verifying algebraic assertions =====\n" in
  let delivered_helper = (&&) in
  let mk_tasks ?comments headers (sid, s) =
    let tasks =
      verify_espec_no_ecut_domains
        ~comments:(
          if !debug then
            rcons_comments_option
              comments
              ("Algebraic assertion #" ^ string_of_int sid
               ^ ": " ^ Ast.Cryptoline.string_of_ebexp_prove_with s.espost)
          else
            []
        )
        headers vgen s hashopt in
    tasks in
  let verify_spec ?comments headers (res, pending) s =
    let tasks = mk_tasks ?comments headers s in
    DomainsTasks.add_to_pending Fun.id delivered_helper res pending tasks in
  (* Check previous result *)
  let verify cid headers (res, pending) (sid, s) =
    if res && Options.Std.mem_hashset_opt options.st_verify_eassert_ids sid
    then verify_spec
        ~comments:(
          if !debug then
            [ "Verify: algebraic assertions";
              Printf.sprintf "Track: %s" options.st_tag;
              "Cut: #" ^ string_of_int cid ]
          else
            []
        )
        headers (res, pending) (sid, s)
    else (res, pending) in
  apply_to_cuts_domains
    options.st_verify_eacuts        (* cut IDs to be verified *)
    verify                          (* verification function *)
    delivered_helper                (* function for delivering results *)
    true                            (* initial result *)
    (DomainsTasks.empty_pending())   (* initial pending state *)
    (cut_eassert (espec_of_spec s)) (* all cuts *)
